#!/bin/bash

###
## Run the weighted pagerank program
## for the semimetric case (before removing triangles)
## or the non-semimetric case (after removing triangleS)
###

if test "$#" -ne 3; then
	echo "Usage: run_pagerank <input_edges> <output_ranks> <#threads>"
	exit
fi


hadoop jar /home/b.vka/workspace/okapi/target/okapi-0.3.5-SNAPSHOT-jar-with-dependencies.jar org.apache.giraph.GiraphRunner ml.grafos.okapi.graphs.SimpleWeightedPageRank -eif ml.grafos.okapi.io.formats.LongDoubleTextEdgeInputFormat -eip $1 -vof ml.grafos.okapi.io.formats.VertexWithDoubleValueDoubleEdgeTextOutputFormat -op $2 -w 1 -ca giraph.outEdgesClass=org.apache.giraph.edge.HashMapEdges -ca giraph.SplitMasterWorker=false -ca giraph.numComputeThreads=$3

