#!/bin/bash

###
## Run the okapi Adamic-Adar Similarity program
###

if test "$#" -ne 3; then
	echo "Usage: run_adamic_adar <input_edges> <output_edges> <#workers>"
	exit
fi
hadoop jar /home/b.vka/workspace/okapi/target/okapi-0.3.5-SNAPSHOT-jar-with-dependencies.jar org.apache.giraph.GiraphRunner ml.grafos.okapi.graphs.AdamicAdarSimilarity\$ComputeLogOfInverseDegree -mc  ml.grafos.okapi.graphs.AdamicAdarSimilarity\$MasterCompute -eif ml.grafos.okapi.io.formats.LongDoubleTextEdgeInputFormat -eip $1 -eof org.apache.giraph.io.formats.SrcIdDstIdEdgeValueTextOutputFormat -op $2 -w 1 -ca giraph.oneToAllMsgSending=true -ca giraph.outEdgesClass=org.apache.giraph.edge.HashMapEdges -ca adamicadar.approximation.enabled=false -ca distance.conversion.enabled=true -ca giraph.SplitMasterWorker=false -ca giraph.numComputeThreads=$3 -ca giraph.numInputThreads=$3 -ca giraph.numOutputThreads=$3
