#!/bin/bash

###
## Run the okapi Jaccard Similarity program
###

if test "$#" -ne 3; then
	echo "Usage: run_jaccard <input_edges> <output_edges> <#threads>"
	exit
fi

 ~/workspace/hadoop-1.2.1/hadoop-1.2.1/bin/hadoop jar /home/b.vka/workspace/okapi/target/okapi-0.3.5-SNAPSHOT-jar-with-dependencies.jar org.apache.giraph.GiraphRunner ml.grafos.okapi.graphs.Similarity\$SendFriendsBloomFilter -mc ml.grafos.okapi.graphs.Similarity\$MasterCompute -eif ml.grafos.okapi.io.formats.LongDoubleZeroReverseTextEdgeInputFormat -eip $1 -eof org.apache.giraph.io.formats.SrcIdDstIdEdgeValueTextOutputFormat -op $2 -w 1 -ca giraph.oneToAllMsgSending=true -ca giraph.outEdgesClass=org.apache.giraph.edge.HashMapEdges -ca jaccard.approximation.enabled=true -ca distance.conversion.enabled=true -ca giraph.SplitMasterWorker=false -ca giraph.numComputeThreads=$3 -ca giraph.numInputThreads=$3 -ca giraph.numOutputThreads=$3
